05-http-server-streams: 01 + 02
js-tasks-ru/nodejs-20201126-2_dariagorchylina pull request #7
Opened 2020-12-13 20:41 UTC by madelGeek

2020-12-13 20:49 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-13 20:55 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-13 21:21 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-14 11:15 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - удаление файла
+ файл должен удаляться
+ если файла нет - ошибка 404
+ если путь вложенный - возвращается ошибка 400
```

Добавляю преподавателя (@RidgeA) для код-ревью, посмотрим что он скажет :)

2020-12-14 11:23 UTC, RidgeA requested changes

2020-12-14 11:23 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +      readFile(filepath, function(error, contents) {
Для данной задачи `pipe` подходит больше, т.к. позволяет работать с файлом маленькими частями, а не всем сразу.
Файл может быть большим - больше чем лимит оперативной памяти для NodeJS процесса и больше чем вообще доступно оперативной памяти.

Попробуйте, пожалуйста, переделать используя `pipe`

2020-12-14 12:06 UTC, madelGeek commented on 05-http-server-streams/01-file-server-get/server.js
> +      readFile(filepath, function(error, contents) {
сделано

2020-12-14 12:49 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-14 13:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
- файл отдается по запросу
- файл отдается по запросу
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - удаление файла
+ файл должен удаляться
+ если файла нет - ошибка 404
+ если путь вложенный - возвращается ошибка 400
```

2020-12-14 16:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-12-14 17:31 UTC, RidgeA approved these changes

2020-12-14 17:31 UTC, merged